### ISSUE TITLE
Provide a Mathjax-like feature in rendering HTML

### ISSUE THREAD

**Issue by StructSeeker** [Myriad-Dreamin/typst.ts#609]
Is it possible for for a [Mathjax-like](https://docs.mathjax.org/en/latest/input/tex/html.html) feature that (configurably) render formula in math mode out-of-the-box?

**Comment by Myriad-Dreamin** [comment]
Since a complete typst compiler takes 20MB, you might not expect to run it in browser. Instead, we can render it at server side:
- SSA solution: https://github.com/Myriad-Dreamin/typst.ts/tree/main/projects/rehype-typst
- Online rendering server solution: typst.tudbut.de
  ![lim_(a->0)(f(x_0+a)-f(x_0))/a=f'(x)](https://typst.tudbut.de/lim_(a->0)(f(x_0+a)-f(x_0))/a=f'(x))
